### ISSUE TITLE
Able to leave ProfileEditing.js without completing it

### ISSUE THREAD

**Issue by Ace314159** [AnchorInc/anchor#17]
In order to prevent it from displaying visual errors, we should not allow the user to leave the screen.
Currently, the only way left that I have found and didn't now how to fix is if the user presses the back button. 

However, the back button should only be disabled if the user hasn't completed the profile. If they are editing it for the second or third time, they should be allowed to press the back button. BTW, the back button refers to the navigation buttons on the bottom of the screen for android.

**Comment by nithindot3513** [comment]
the user can now only save valid updates. back functionality shouldn't be blocked in case a user accidentally enters a screen. they can only save valid updates

**Comment by Ace314159** [comment]
When you first log in, in order for the rest of the app to work, we need the user to complete their profile with phone no and stuff. In that case, we need to prevent them leaving. In all other cases, I agree with what you said, and they should be allowed to go back.

**Comment by SpyKing** [comment]
I agree with Akash, we need to find a way to disable the back button in the profile when it's the first time

**Comment by nithindot3513** [comment]
I was reviewing the code and it looks like someone has fixed it. resolving the issue
