### ISSUE TITLE
teachersetup slowing down

### ISSUE THREAD

**Issue by nithindot3513** [AnchorInc/anchor#8]
the code in teacher setup needs to be optimized to prevent frame drops and long pauses.

**Comment by SpyKing** [comment]
could you be more specific, what exactly is slow>

**Comment by Ace314159** [comment]
The whole logging in and signing up is really slow, and sometimes it never terminates. And the profile picture is not loaded up when the teacher logs in for the first time.

**Comment by nithindot3513** [comment]
fixed the frame drops, and the profile not loading. the choppy slider has also been fixed

**Comment by Ace314159** [comment]
Just wondering, what was causing the frame drops
